name: Build and pull Docker Image

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github acitons
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
         echo "VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV
        
      - name: Check if tag exists
        run: |
          if docker pull ishaasampla/personal-portfolio:$VERSION; then
            echo "Tag already exists!"
            exit 1
          fi
        
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/personal-portfolio
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest
            type=raw,value=main
            type=sha

      - name:  Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with: 
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}

